Design Revamp: Dashboard
CalCourse-Dev/CalCourse_FrontEnd pull request #18
Opened 2023-06-06 05:56 UTC by akmazian

Dashboard 功能上全线修好了！
- 解决了搜索时不识别简写的问题（比如 `cs` 和 `compsci`）
  - 实现了对课号带 `c` 的课程搜索（比如 `data 100` 可以搜出 `data c100`）
- Design 的部分基本上完全做完了，有一些还在讨论的部分没有做
- 再次提高了搜索 & 首次加载时的速度

另外删除了一些不需要的 components & files

完善了 tailwind theme

2023-06-07 11:38 UTC, HuanzhiMao commented
Nice work! See the Review Comment for issues. Let me know if you have any questions.

2023-06-08 01:53 UTC, HuanzhiMao requested changes

2023-06-08 01:53 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
>      const parse_search_string = (search_string: string): string => {
parse_search_string有误判的情况。比如"EECS 127", "PHYSICS 7A"这些课名里的"cs"会在当前逻辑下被强制替换成"compsci", 导致搜索不出结果。可以考虑通过强制”全字匹配“来解决。另外关于空格的问题。比如"CS61A"目前是搜不出结果的，但是"CS 61A"可以，所有我觉得我们parse的时候需要再加一步，在合适的地方插入空格(一个思路，可以考虑第一个字母和数字交接的地方，因为字母大概率是department number，而数字是course number)

2023-06-08 01:53 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
> +    const terms: ITerm[] = [
terms那个ITerm interface里我们现在是hard-code进去了缩写和全称的对应关系，比如'UCB Su23'对应'Summer 2023'。我觉得我们可以通过获取当前的日期来自动生成terms，几个简单的if-else就可以。比如现在日期是2023年6月7号，属于summer session的时候，那么就应该是Su23, Fa23和Sp24（是Sp24而不是Sp23是因为spring semester已经过了，所以没有必要再展示旧的二维码了）。

2023-06-08 01:53 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
> +                    .includes(selected_term.school_name_and_term.toLowerCase())
一个小点，这边其实可以直接用string equal

2023-06-08 01:53 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
> +                        parseInt((course2.course_name.match(/\d+/) ?? ['0'])[0])
这边直接调用course_id会更简单一些

2023-06-08 01:53 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
> +    const remove_leading_c = (search_string: string): string => {
We also have leading W and N; we should consider removing them as well. For example, "MATH N54", "MATH W54" (W54 means online, which is usually offered during the summer).

2023-06-08 01:53 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
> +                        ).includes(parse_search_string(search_string)) ||
这边逻辑需要好好修改一下了。比如"Data C100"这课，现在你输Data 100是有结果的，但其他的比如Data100, DataC100, Data C100都是不行的。我们数据库里存的课号就是Data C100（因为这是官方的课号），所以如果你对于search string去remove leading c的话，course_name那边也需要进行相应的操作。

2023-06-08 01:53 UTC, HuanzhiMao commented on web/src/components/Dashboard/CourseCard/CourseCard.component.tsx
> +class CourseCard extends Component<PCourseCard, SCourseCard> {
对于专业群和Cal Life的群聊卡片，在鼠标点上去的时候，下面底栏的course_id依然存在，比如它会显示"20001二手交易群"而不是"二手交易群"。鉴于这些群聊的course_id其实没啥用，我们可以考虑直接不显示？

2023-06-08 01:59 UTC, akmazian commented on web/src/components/Dashboard/Dashboard.tsx
> +                        parseInt((course2.course_name.match(/\d+/) ?? ['0'])[0])
这个感觉看起来会更直观一点，先上来的都是各种 1a 1b 的课感觉比较符合大家一般思考的逻辑。很少会有人说 okay 排在前面的课应该是课号比较小的

2023-06-08 01:59 UTC, akmazian commented on web/src/components/Dashboard/Dashboard.tsx
> +    const remove_leading_c = (search_string: string): string => {
fixed

2023-06-08 02:04 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
> +                        parseInt((course2.course_name.match(/\d+/) ?? ['0'])[0])
你说的也有道理

2023-06-08 02:11 UTC, akmazian commented on web/src/components/Dashboard/Dashboard.tsx
> +    const terms: ITerm[] = [
但我们现在 spring 24 的群建好了吗或许

2023-06-08 02:32 UTC, akmazian commented on web/src/components/Dashboard/Dashboard.tsx
>      const parse_search_string = (search_string: string): string => {
- [x] 误判（加了检索符，必须得是以 cs 开头的才会被 replace，鉴于没有专业的全称是别的专业的缩写开头的，就没有考虑比如 csee 这种情况）
- [x] 空格问题（最后加了一个加空格确保格式，现在 data100 data c100 data 100 都能检索出来了。datac100 没有加适配，感觉不太会有这样的问题？）

2023-06-08 02:32 UTC, akmazian commented on web/src/components/Dashboard/Dashboard.tsx
> +                        ).includes(parse_search_string(search_string)) ||
fixed

2023-06-08 02:34 UTC, akmazian commented on web/src/components/Dashboard/Dashboard.tsx
> +    const terms: ITerm[] = [
思考了一下，这里感觉可以稍微先放一下，等 user context 做好了之后再做。这样方便抓取用户的学校以及对不同学校 semester / quarter 时间不一样的适配。

2023-06-08 02:43 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
>      const parse_search_string = (search_string: string): string => {
Data100现在好了。datac100我觉得可以不用管，毕竟一般也没人那么输。
Fall23的"PHYSICS 7A"似乎依然有问题；physics全系的都出不来诶

2023-06-08 03:09 UTC, HuanzhiMao commented on web/src/components/Dashboard/Dashboard.tsx
> +    const terms: ITerm[] = [
嗯，我同意可以等user context。
这边的想法就是，因为后端会直接返回所有学期的二维码，包括那些已经过时的，所以我们在前端process的时候就加一个filter，那些之前学期的就直接discard掉。所以如果现在的时间已经是summer 23了，那之前spring 23的二维码就应该被判为过期；唯一valid的spring学期就是spring 24。这和spring 24的群有没有建好没关系

2023-06-08 05:27 UTC, akmazian commented on web/src/components/Dashboard/Dashboard.tsx
>      const parse_search_string = (search_string: string): string => {
- [ ] 把匹配变成全词匹配，搜索的时候对类似于 datac100 的情况做适配

2023-06-09 00:20 UTC, akmazian commented
都修好啦！没有问题的话应该可以 merge 了

2023-06-09 06:00 UTC, HuanzhiMao approved these changes

2023-06-09 06:00 UTC, merged